name: Padavan Firmware Build

on:
  workflow_dispatch:  # 手动触发编译

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt-get install -y \
            unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio git python3-docutils gettext automake autopoint \
            texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin

      - name: Download toolchain
        run: |
          cd toolchain-mipsel
          ./dl_toolchain.sh

      - name: Build firmware for CR660x
        run: |
          cd trunk
          fakeroot ./build_firmware_modify CR660x

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: Firmware-CR660x
          path: trunk/images/*.trx
